### ISSUE TITLE
Stellar - wrong informations

### ISSUE THREAD

**Issue by burningtree** [opencrypto-io/data#50]
Please remove all exchanges which don't maintain Stellar Foundation

For example on "stellarterm" is written:
> The project is independent of the Stellar Development Foundation.

Another issue is that asset of Stellar is named "Lumens" not, "Stellar"
https://www.stellar.org/lumens/

Who reviewed this?

**Comment by cryptomari0** [comment]
Name of the asset was changed from Stellar to Lumen. Source:
https://www.mystellar.org/thread-86.html
https://www.stellar.org/lumens/

If we talk about the exchanges, I am not sure. It's decentralized open sources exchange:
stellarterm - developed by Iris Li from the Stellar team (former member)
stellarport - using DEX (Stellar decentralized exchange), so it's not actually exchange of the project, but in other hand, exchange build on the project tool
interstellar - powered by the project Stellar #51

**Comment by burningtree** [comment]
Best will be add exchanges to project only if we have proof that they really maintain it.

**Comment by cryptomari0** [comment]
But build on the Stellar network. You cannot say that Bitfinex is build on some projects network

**Comment by burningtree** [comment]
Thats cool, but not have any relevance. There is thousands project build on Ethereum, but that non means that we put all to Ethereum project.
For example - OasisDEX is decentralized exchange build on Ethereum Network and maintained by MakerDAO project. So its located in MakerDAO project, not Ethereum.

**Comment by burningtree** [comment]
I did some research and it looks that orderbooks on Stellarport & Stellarterm is the same. They use same engine/protocol which is named `Stellar Decentralized Exchange` or `Stellar Distributed Exchange` - and that's part of Stellar project ([source][1]). 
It's similar like 0x protocol (Ethereum), but Stellar have this protocol built-in.

It would be good to capture it somehow to database, but i'm not sure how.


[1]: https://www.stellar.org/developers/guides/concepts/exchange.html

**Comment by burningtree** [comment]
I suggest adding `platform` property to Exchange schema. Values for example: `stellar`, `bitshares` or `ethereum:0x`.

**Comment by cryptomari0** [comment]
OK, I have deleted the exchanges from Stellar right now #51 

Platform created for exchanges (suggestion) 

Changelog updated:
https://github.com/opencrypto-io/schema/blob/master/CHANGELOG.md

**Comment by burningtree** [comment]
👍
